# cat image concepts are original cat images (non poluted with labels)

#  generated by chat-gpt


import os
import random
import argparse
import shutil

def sample_images(src_dir: str, n: int, out_dir: str):
    # Validate input directory
    if not os.path.isdir(src_dir):
        raise NotADirectoryError(f"Source directory does not exist: {src_dir}")

    # Collect image files (case-insensitive common image extensions)
    valid_exts = {".jpg", ".jpeg", ".png", ".bmp", ".gif", ".tiff", ".webp"}
    images = [f for f in os.listdir(src_dir)
              if os.path.splitext(f)[1].lower() in valid_exts]

    if not images:
        raise FileNotFoundError("No image files found in the source directory.")

    if n > len(images):
        raise ValueError(f"Requested {n} images, but only {len(images)} available.")

    # Create output directory
    out_path = os.path.join(src_dir, out_dir)
    os.makedirs(out_path, exist_ok=True)

    # Randomly sample and copy
    sampled = random.sample(images, n)
    for img in sampled:
        shutil.copy2(os.path.join(src_dir, img), os.path.join(out_path, img))

    print(f"Successfully copied {n} images to: {out_path}")

def main():
    parser = argparse.ArgumentParser(
        description="Randomly sample N images from a directory and copy them to a subdirectory."
    )
    parser.add_argument("--src", required=True, help="Path to source directory containing images.")
    parser.add_argument("--n", type=int, required=True, help="Number of images to sample.")
    parser.add_argument("--out", default="sampled_images", help="Name of output subdirectory.")
    args = parser.parse_args()

    sample_images(args.src, args.n, args.out)

if __name__ == "__main__":
    main()



