#!/usr/bin/env python3
# generated by claude
"""
Script to copy images from a directory and add text labels to each image.
Usage: python label_images.py <directory_path> <label_text>
"""

import os
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import shutil

def get_font(size=40):
    """Try to get a nice font, fall back to default if unavailable."""
    try:
        # Try to use a common system font
        return ImageFont.truetype("arial.ttf", size)
    except:
        try:
            return ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", size)
        except:
            # Fall back to default font
            return ImageFont.load_default()

def add_label_to_image(input_path, output_path, label_text, position="top"):
    """
    Add text label to an image and save it.
    
    Parameters:
        input_path (str): Path to input image.
        output_path (str): Path to save labeled image.
        label_text (str): Text to overlay.
        position (str): 'top' (default) or 'bottom' for text box location.
    """
    try:
        img = Image.open(input_path)

        if img.mode != 'RGB':
            img = img.convert('RGB')

        draw = ImageDraw.Draw(img)
        font_size = 40
        font = get_font(font_size)

        # Compute text size
        bbox = draw.textbbox((0, 0), label_text, font=font)
        text_width = bbox[2] - bbox[0]
        text_height = bbox[3] - bbox[1]

        # Horizontal center
        x = (img.width - text_width) // 2
        padding = 8

        # Determine vertical position based on parameter
        if position.lower() == "bottom":
            y = img.height - text_height - (padding * 3)
        else:
            y = 10  # default top

        # Draw background rectangle (black box for contrast)
        draw.rectangle(
            [x - padding, y - padding, x + text_width + padding, y + text_height + padding],
            fill='black'
        )

        # Draw text (white)
        draw.text((x, y), label_text, fill='white', font=font)

        img.save(output_path, quality=95)
        return True

    except Exception as e:
        print(f"Error processing {input_path}: {e}")
        return False


def process_directory(dir_path, label,position="top"):
    """Process all images in a directory and create labeled copies."""
    # Define supported image extensions
    image_extensions = {'.jpg', '.jpeg', '.png', '.bmp', '.gif', '.tiff', '.webp'}
    
    # Get the directory path
    source_dir = Path(dir_path)
    
    # Check if source directory exists
    if not source_dir.exists():
        print(f"Error: Directory '{dir_path}' does not exist.")
        return
    
    if not source_dir.is_dir():
        print(f"Error: '{dir_path}' is not a directory.")
        return
    
    # Create new directory name
    parent_dir = source_dir.parent
    old_dir_name = source_dir.name
    new_dir_name = f"{old_dir_name}-{label}"
    new_dir_path = parent_dir / new_dir_name
    
    # Create new directory
    try:
        new_dir_path.mkdir(exist_ok=True)
        print(f"Created directory: {new_dir_path}")
    except Exception as e:
        print(f"Error creating directory: {e}")
        return
    
    # Process all images in the source directory
    image_count = 0
    processed_count = 0
    
    for file_path in source_dir.iterdir():
        if file_path.is_file() and file_path.suffix.lower() in image_extensions:
            image_count += 1
            output_path = new_dir_path / file_path.name
            
            print(f"Processing: {file_path.name}")
            if add_label_to_image(file_path, output_path, label,position=position):
                processed_count += 1
        
        # break
    
    # Summary
    print(f"\n{'='*50}")
    print(f"Processing complete!")
    print(f"Total images found: {image_count}")
    print(f"Successfully processed: {processed_count}")
    print(f"Output directory: {new_dir_path}")
    print(f"{'='*50}")

def main():
    """Main function to parse arguments and run the script."""
    if len(sys.argv) < 3:
        print("Usage: python label_images.py <directory_path> <label_text> <position>")
        print("Example: python label_images.py ./my_images 'Sample Label' 'bottom' ")
        sys.exit(1)
    
    dir_path = sys.argv[1]
    label = sys.argv[2]

    position = "top"
    if len(sys.argv) > 3 :
        position = sys.argv[3]
    
    process_directory(dir_path, label,position)

if __name__ == "__main__":
    main()